/*
 * Copyright 2005 University of Manchester
 *
 *  This file is part of Taverna.  Further information, and the
 *  latest version, can be found at http://taverna.sf.net
 * 
 *  Taverna is in turn part of the myGrid project, more details
 *  can be found at http://www.mygrid.org.uk
 *
 *  Taverna is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as
 *  published by the Free Software Foundation; either version 2.1
 *  of the License, or (at your option) any later version.
 *
 *  Taverna is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with Taverna; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package net.sf.taverna.ocula.action;

import java.util.Map;

import net.sf.taverna.ocula.Ocula;

/**
 * Users of the {@link ProcessFieldsAction} are required to implement this
 * interface. It provides a sole method that processes the data generated by
 * the action.
 * 
 * @author Ismael Juma (ismael@juma.me.uk)
 *
 */
public interface Processor {

    /**
     * Processes the data in <code>map</code>.
     * @param map A Map where the key is the name attribute of &lt;text&gt; and
     * 		  the value is the text contained in it when the action was
     * 		  initiated.
     * @param ocula Ocula instance.
     * @throws Exception if a problem ocurred while processing the map.
     */
    public void process(Map map, Ocula ocula) throws Exception;
}
