package net.sf.taverna.t2.platform.raven;

import java.net.URL;
import java.util.List;
import java.util.Set;

import net.sf.taverna.t2.platform.pom.ArtifactIdentifier;

/**
 * Defines a method for the construction of a class loader based on a Maven 2
 * artifact. This class loader will inherit from a parent and delegate to a set
 * of child class loaders based on the Maven 2 meta-data defined for the
 * artifact.
 * 
 * @author Tom Oinn
 */
public interface Raven {

	/**
	 * Given an artifact identifier, retrieve or construct a class loader that
	 * can instantiate classes defined by that artifact's corresponding jar
	 * file. Note - the repository list is only used if the class loader is
	 * constructed, implementations may (and should) cache this information so
	 * subsequent calls with different repository location argument will in
	 * effect be ignored.
	 * <p>
	 * Do not make any assumptions about the type of class loader returned, if
	 * the artifact specified is a system artifact you may simply get the system
	 * class loader back.
	 * <p>
	 * If the appropriate artifacts have not been downloaded this method will
	 * block until they are available.
	 * 
	 * @param id
	 * @param repositories
	 * @return
	 * @throws RavenException
	 *             if any problems occur when instantiating and returning the
	 *             new class loader(s)
	 */
	public ClassLoader getLoader(ArtifactIdentifier id, List<URL> repositories)
			throws RavenException;

	/**
	 * Get the system artifact set for this Raven instance. A system artifact is
	 * never downloaded, instead it is assumed that the client has provided it
	 * in some way on the parent class loader or some indirect parent thereof.
	 * 
	 * @return the current set of system artifacts, this should return an
	 *         unmodifiable copy of the system artifact set, do not attempt to
	 *         modify the system artifact set through Set methods on the
	 *         returned value.
	 */
	public Set<ArtifactIdentifier> getSystemArtifactSet();

	/**
	 * Gets the parent class loader to be used for class loaders generated by
	 * this Raven instance. The parent loader is searched before any artifact
	 * jar class loaders, and is expected to provide artifacts that are
	 * specified in the system artifact list.
	 */
	public ClassLoader getParentClassLoader();

}
