package net.sf.taverna.t2.reference.impl;

import net.sf.taverna.t2.reference.T2Reference;
import net.sf.taverna.t2.reference.T2ReferenceGenerator;
import net.sf.taverna.t2.reference.T2ReferenceType;

/**
 * Simple implementation of T2ReferenceGenerator intended to be injected into
 * the service layers for integration testing. Exposes a namespace property
 * which can be configured through spring and allocates local parts based on an
 * integer counter - this is only guaranteed to be unique within a single
 * instance of this object so isn't suitable for real production use. For proper
 * usage use an implementation tied to the backing store you're putting t2
 * reference objects into.
 * 
 * @author Tom Oinn
 * 
 */
public class SimpleT2ReferenceGenerator implements T2ReferenceGenerator {

	private String namespace = "testNS";
	private String localPrefix = "test";
	private int counter = 0;

	/**
	 * Set the namespace for identifiers generated by this class as a string
	 * 
	 * @param newNamespace
	 *            the namespace to use
	 */
	public void setNamespace(String newNamespace) {
		this.namespace = newNamespace;
	}

	/**
	 * Get the namespace for identifiers generated by this class
	 */
	public String getNamespace() {
		return namespace;
	}

	private synchronized String getNextLocalPart() {
		return localPrefix + (counter++);
	}

	public synchronized T2Reference nextReferenceSetReference() {
		T2ReferenceImpl r = new T2ReferenceImpl();
		r.setNamespacePart(getNamespace());
		r.setLocalPart(getNextLocalPart());
		r.setReferenceType(T2ReferenceType.ReferenceSet);
		r.setDepth(0);
		r.setContainsErrors(false);
		return r;
	}

	public T2Reference nextListReference(boolean containsErrors, int listDepth) {
		T2ReferenceImpl r = new T2ReferenceImpl();
		r.setNamespacePart(getNamespace());
		r.setLocalPart(getNextLocalPart());
		r.setReferenceType(T2ReferenceType.IdentifiedList);
		r.setDepth(listDepth);
		r.setContainsErrors(containsErrors);
		return r;
	}

}
