#
#  collect all  <process> <used> <artifact> relationships
#

PREFIX    a:  <http://www.ipaw.info/2007/opm#>
PREFIX    b:  <http://taverna.opm.org/>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?process ?usedArtifact ?role ?processIteration
		
WHERE
{ 
      ?usedInstance a:usedArtifact ?artifactResource .
      ?usedInstance a:usedByProcess ?processResource .
      ?usedInstance a:usedRole      ?roleResource .
      ?processResource rdfs:label ?process .
      ?artifactResource rdfs:label ?usedArtifact .
      ?roleResource rdfs:label ?role 
      OPTIONAL {  ?processResource b:iteration ?processIteration }
 }  
