/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_taverna_matserver_MatEngineImpl */

#ifndef _Included_net_sf_taverna_matserver_MatEngineImpl
#define _Included_net_sf_taverna_matserver_MatEngineImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_taverna_matserver_MatEngineImpl
 * Method:    execute
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_sf_taverna_matserver_MatEngineImpl_execute
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_sf_taverna_matserver_MatEngineImpl
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_taverna_matserver_MatEngineImpl_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
