PREFIX b:    <http://taverna.opm.org/>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX a:     <http://www.ipaw.info/2007/opm#>

SELECT ?gb ?r
{
    ?gb rdf:type a:Generated .
    ?u a:generatedRole ?r
}
