/* CVS $Id: ProvenanceVocab.java,v 1.1 2007-12-14 12:49:09 stain Exp $ */
package uk.ac.man.cs.img.mygrid.provenance.knowledge.ontology.jena; 
import com.hp.hpl.jena.ontology.DatatypeProperty;
import com.hp.hpl.jena.ontology.ObjectProperty;
import com.hp.hpl.jena.ontology.OntClass;
import com.hp.hpl.jena.ontology.OntModel;
import com.hp.hpl.jena.ontology.OntModelSpec;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;
/**
 * Vocabulary definitions from provenance.owl 
 * @author Auto-generated by schemagen on 26 May 2006 10:34 
 */
public class ProvenanceVocab {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.mygrid.org.uk/provenance#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
        
    public static final ObjectProperty CONTAINS_DATA = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#containsData" );
    
    public static final ObjectProperty INPUT_DATA_HAS_NAME = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#inputDataHasName" );
    
    public static final ObjectProperty HAS_PROPERTY = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#hasProperty" );
    
    public static final ObjectProperty DATA_WRAPPED_INTO = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#dataWrappedInto" );
    
    public static final ObjectProperty USER_PREDICATE = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#userPredicate" );
    
    public static final ObjectProperty DATA_DERIVED_FROM = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#dataDerivedFrom" );
    
    public static final ObjectProperty NESTED_RUN = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#nestedRun" );
    
    public static final ObjectProperty BELONGS_TO = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#belongsTo" );
    
    public static final ObjectProperty WORKFLOW_OUTPUT = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#workflowOutput" );
    
    public static final ObjectProperty PROCESS_OUTPUT = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#processOutput" );
    
    public static final ObjectProperty DATA_HAS_NAME = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#dataHasName" );
    
    public static final ObjectProperty NESTED_WORKFLOW = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#nestedWorkflow" );
    
    public static final ObjectProperty ITERATION = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#iteration" );
    
    public static final ObjectProperty OLD_DATA_OBJECT = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#oldDataObject" );
    
    public static final ObjectProperty RUNS_WORKFLOW = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#runsWorkflow" );
    
    public static final ObjectProperty PROCESS_INPUT = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#processInput" );
    
    public static final ObjectProperty OUTPUT_DATA_HAS_NAME = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#outputDataHasName" );
    
    public static final ObjectProperty LAUNCHED_BY = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#launchedBy" );
    
    public static final ObjectProperty WORKFLOW_INPUT = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#workflowInput" );
    
    public static final ObjectProperty EXECUTED_PROCESS_RUN = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#executedProcessRun" );
    
    public static final ObjectProperty RUNS = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#runs" );
    
    public static final ObjectProperty RUNS_PROCESS = m_model.createObjectProperty( "http://www.mygrid.org.uk/provenance#runsProcess" );
    
    public static final DatatypeProperty VALUE = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/provenance#value" );
    
    public static final DatatypeProperty END_TIME = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/provenance#endTime" );
    
    public static final DatatypeProperty START_TIME = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/provenance#startTime" );
    
    public static final DatatypeProperty CLASS_NAME = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/provenance#className" );
    
    public static final DatatypeProperty DATA_SYNTACTIC_TYPE = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/provenance#dataSyntacticType" );
    
    public static final DatatypeProperty WORKFLOW_TITLE = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/provenance#workflowTitle" );
    
    public static final DatatypeProperty KEY = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/provenance#key" );
    
    public static final DatatypeProperty WORKFLOW_DESCRIPTION = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/provenance#workflowDescription" );
    
    public static final DatatypeProperty WORKFLOW_AUTHOR = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/provenance#workflowAuthor" );
    
    public static final DatatypeProperty WORKFLOW_INITIAL_LSID = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/provenance#workflowInitialLSID" );
    
    public static final DatatypeProperty CAUSE = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/provenance#cause" );
    
    public static final DatatypeProperty NUMBER_OF_ITERATIONS = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/provenance#numberOfIterations" );
    
    public static final DatatypeProperty MIME_TYPE = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/provenance#mimeType" );
    
    public static final OntClass NESTED_WORKFLOW_PROCESS_RUN = m_model.createClass( "http://www.mygrid.org.uk/provenance#NestedWorkflowProcessRun" );
    
    public static final OntClass DATA_NAME = m_model.createClass( "http://www.mygrid.org.uk/provenance#DataName" );
    
    public static final OntClass PROCESS_PROPERTY = m_model.createClass( "http://www.mygrid.org.uk/provenance#ProcessProperty" );
    
    public static final OntClass ATOMIC_DATA = m_model.createClass( "http://www.mygrid.org.uk/provenance#AtomicData" );
    
    public static final OntClass FAILED_RUN = m_model.createClass( "http://www.mygrid.org.uk/provenance#FailedRun" );
    
    public static final OntClass PROCESS_ITERATION = m_model.createClass( "http://www.mygrid.org.uk/provenance#ProcessIteration" );
    
    public static final OntClass DATA_OBJECT = m_model.createClass( "http://www.mygrid.org.uk/provenance#DataObject" );
    
    public static final OntClass PROCESS_RUN = m_model.createClass( "http://www.mygrid.org.uk/provenance#ProcessRun" );
    
    /** <p>Navigate ontology starting from here</p> */
    public static final OntClass WORKFLOW_RUN = m_model.createClass( "http://www.mygrid.org.uk/provenance#WorkflowRun" );
    
    public static final OntClass OUTPUT_DATA_NAME = m_model.createClass( "http://www.mygrid.org.uk/provenance#OutputDataName" );
    
    public static final OntClass PROCESS_RUN_WITH_ITERATIONS = m_model.createClass( "http://www.mygrid.org.uk/provenance#ProcessRunWithIterations" );
    
    public static final OntClass EXPERIMENTER = m_model.createClass( "http://www.mygrid.org.uk/provenance#Experimenter" );
    
    public static final OntClass WORKFLOW = m_model.createClass( "http://www.mygrid.org.uk/provenance#Workflow" );
    
    public static final OntClass FAILED_NESTED_WORKFLOW_RUN = m_model.createClass( "http://www.mygrid.org.uk/provenance#FailedNestedWorkflowRun" );
    
    public static final OntClass FAILED_WORKFLOW_RUN = m_model.createClass( "http://www.mygrid.org.uk/provenance#FailedWorkflowRun" );
    
    public static final OntClass FAILED_PROCESS_RUN = m_model.createClass( "http://www.mygrid.org.uk/provenance#FailedProcessRun" );
    
    public static final OntClass RUN = m_model.createClass( "http://www.mygrid.org.uk/provenance#Run" );
    
    public static final OntClass DATA_COLLECTION = m_model.createClass( "http://www.mygrid.org.uk/provenance#DataCollection" );
    
    public static final OntClass CHANGED_DATA_OBJECT = m_model.createClass( "http://www.mygrid.org.uk/provenance#ChangedDataObject" );
    
    public static final OntClass RUNNABLE = m_model.createClass( "http://www.mygrid.org.uk/provenance#Runnable" );
    
    public static final OntClass ORGANIZATION = m_model.createClass( "http://www.mygrid.org.uk/provenance#Organization" );
    
    public static final OntClass INPUT_DATA_NAME = m_model.createClass( "http://www.mygrid.org.uk/provenance#InputDataName" );
    
    public static final OntClass NESTED_WORKFLOW_RUN = m_model.createClass( "http://www.mygrid.org.uk/provenance#NestedWorkflowRun" );
    
    public static final OntClass PROCESS = m_model.createClass( "http://www.mygrid.org.uk/provenance#Process" );

}
