package net.sf.taverna.t2.component;

import net.sf.taverna.t2.visit.VisitKind;
import net.sf.taverna.t2.visit.Visitor;

public class ComponentHealthCheck extends VisitKind {

	  // The following values indicate the type of results that can be associated
	  // with a VisitReport generated by a health-checking visitor.

	  public static final int NO_PROBLEM= 0;
	  public static final int OUT_OF_DATE = 10;
	  
	  
	  @Override
	  public Class<? extends Visitor> getVisitorClass() {
	    return ComponentActivityUpgradeChecker.class;
	  }
	  
	  private static class Singleton {
	    private static ComponentHealthCheck instance = new ComponentHealthCheck();
	  }
	  
	  public static ComponentHealthCheck getInstance() {
	    return Singleton.instance;
	  }

}
