require 'rubygems' 
Gem::manage_gems 
require 'rake/gempackagetask' 

spec = Gem::Specification.new do |s| 
	s.name = "taverna" 
	s.version = "0.5.1" 
	s.author = "David Withers" 
	s.email = "david.withers@manchester.ac.uk" 
	s.homepage = "http://www.mygrid.org.uk/" 
	s.platform = Gem::Platform::RUBY 
	s.summary = "Support for interacting with the Taverna workflow system" 
	s.files = FileList["{test,lib,docs}/**/*"].exclude("rdoc", "password.txt").to_a 
	s.require_path = "lib" 
	s.autorequire = "baclava,client,document,scufl" 
	s.test_file = "test/ts_taverna.rb" 
	s.has_rdoc = true 
	s.extra_rdoc_files = ["README", "LICENCE"] 
end

Rake::GemPackageTask.new(spec) do |pkg| 
	pkg.need_tar = true 
end 
