PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX o: <http://www.mygrid.org.uk/testrepo/o/>
PREFIX : <http://www.mygrid.org.uk/testrepo/>
SELECT DISTINCT ?run ?using
WHERE {
    ?got_port o:match ?exp_port . 
    ?run o:returned ?got_port .
    ?run o:runs ?test . 
    ?run o:uses ?using
}
