PREFIX b:    <http://ns.taverna.org.uk/2011/provenance/opm/>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX a:     <http://www.ipaw.info/2007/opm#>

SELECT ?u ?r
{
    ?u rdf:type a:Used  .
    ?u a:usedRole ?r
}
