#
#  collect all  <process> <wasge> <artifact> relationships
#

PREFIX    a:  <http://www.ipaw.info/2007/opm#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT  ?artifact ?generatedByProcess ?role
		
WHERE
{ 
      ?generatedBy a:generatedArtifact ?artifactResource .
      ?generatedBy a:generatedByProcess ?processResource .
      ?generatedBy a:generatedRole      ?roleResource .
      ?processResource rdfs:label ?generatedByProcess .
      ?artifactResource rdfs:label ?artifact .
      ?roleResource rdfs:label ?role
 }