/*
 * MatlabTokenMarker.java - matlab token marker
 *
 * You may use and modify this package for any purpose. Redistribution is
 * permitted, in both source and binary form, provided that this notice
 * remains intact in all source distributions of this package.
 */

package net.sf.taverna.t2.matlabactivity.views;

import javax.swing.text.Segment;
import org.syntax.jedit.KeywordMap;
import org.syntax.jedit.tokenmarker.Token;
import org.syntax.jedit.tokenmarker.TokenMarker;

/**
 * 
 * @author petarj
 */
public class MatlabTokenMarker extends TokenMarker {

	private static KeywordMap keywords;
	private int lastOffset;
	private int lastKeyword;

	public MatlabTokenMarker() {
	}

	protected byte markTokensImpl(byte token, Segment line, int lineIndex) {
		char[] array = line.array;
		int offset = line.offset;
		lastOffset = offset;
		lastKeyword = offset;
		int len = line.count + offset;
		boolean backslash = false;

		loop: for (int i = offset; i < len; i++) {
			int i1 = (i + 1);

			char c = array[i];
			if (c == '\\') {
				backslash = !backslash;
				continue;
			}

			switch (token) {
			case Token.NULL:
				switch (c) {
				case '%':
					if (backslash)
						backslash = false;
					else {
						doKeyword(line, i, c);
						addToken(i - lastOffset, token);
						addToken(len - i, Token.COMMENT1);
						lastOffset = lastKeyword = len;
						break loop;
					}
					break;

				case '\'':
					doKeyword(line, i, c);
					if (backslash)
						backslash = false;
					else {
						addToken(i - lastOffset, token);

						token = Token.LITERAL1;
						lastOffset = lastKeyword = i;
					}
					break;
				default:
					backslash = false;
					if (!Character.isLetterOrDigit(c) && c != '_')
						doKeyword(line, i, c);
					break;
				}
				break;
			case Token.LITERAL1:
				if (backslash)
					backslash = false;
				else if (c == '\'') {
					addToken(i1 - lastOffset, Token.LITERAL1);
					token = Token.NULL;
					lastOffset = lastKeyword = i1;
				}
				break;
			default:
				throw new InternalError("Invalid state: " + token);
			}
		}

		switch (token) {
		case Token.NULL:
			doKeyword(line, len, '\0');
		default:
			addToken(len - lastOffset, token);
			break;
		}

		return token;
	}

	private boolean doKeyword(Segment line, int i, char c) {
		int i1 = i + 1;

		int len = i - lastKeyword;
		byte id = keywords.lookup(line, lastKeyword, len);
		if (id != Token.NULL) {
			if (lastKeyword != lastOffset)
				addToken(lastKeyword - lastOffset, Token.NULL);
			addToken(len, id);
			lastOffset = i;
		}
		lastKeyword = i1;
		return false;
	}

	static {
		keywords = new KeywordMap(false);
		keywords.add("all", Token.KEYWORD1);
		keywords.add("any", Token.KEYWORD1);
		keywords.add("exist", Token.KEYWORD1);
		keywords.add("find", Token.KEYWORD1);
		keywords.add("is", Token.KEYWORD1);
		keywords.add("isa", Token.KEYWORD1);
		keywords.add("logical", Token.KEYWORD1);
		keywords.add("mislocked", Token.KEYWORD1);

		keywords.add("builtin", Token.KEYWORD2);
		keywords.add("eval", Token.KEYWORD2);
		keywords.add("evalc", Token.KEYWORD2);
		keywords.add("evalin", Token.KEYWORD2);
		keywords.add("feval", Token.KEYWORD2);
		keywords.add("function", Token.KEYWORD2);
		keywords.add("global", Token.KEYWORD2);
		keywords.add("nargchk", Token.KEYWORD2);
		keywords.add("persistent", Token.KEYWORD2);
		keywords.add("script", Token.KEYWORD2);
		keywords.add("break", Token.KEYWORD2);
		keywords.add("case", Token.KEYWORD2);
		keywords.add("catch", Token.KEYWORD2);
		keywords.add("else", Token.KEYWORD2);
		keywords.add("elseif", Token.KEYWORD2);
		keywords.add("end", Token.KEYWORD2);
		keywords.add("error", Token.KEYWORD2);
		keywords.add("for", Token.KEYWORD2);
		keywords.add("if", Token.KEYWORD2);
		keywords.add("otherwise", Token.KEYWORD2);
		keywords.add("return", Token.KEYWORD2);
		keywords.add("switch", Token.KEYWORD2);
		keywords.add("try", Token.KEYWORD2);
		keywords.add("warning", Token.KEYWORD2);
		keywords.add("while", Token.KEYWORD2);
		keywords.add("input", Token.KEYWORD2);
		keywords.add("keyboard", Token.KEYWORD2);
		keywords.add("menu", Token.KEYWORD2);
		keywords.add("pause", Token.KEYWORD2);
		keywords.add("class", Token.KEYWORD2);
		keywords.add("double", Token.KEYWORD2);
		keywords.add("inferiorto", Token.KEYWORD2);
		keywords.add("inline", Token.KEYWORD2);
		keywords.add("int8", Token.KEYWORD2);
		keywords.add("int16", Token.KEYWORD2);
		keywords.add("int32", Token.KEYWORD2);
		keywords.add("isa", Token.KEYWORD2);
		keywords.add("loadobj", Token.KEYWORD2);
		keywords.add("saveobj", Token.KEYWORD2);
		keywords.add("single", Token.KEYWORD2);
		keywords.add("superiorto", Token.KEYWORD2);
		keywords.add("uint8", Token.KEYWORD2);
		keywords.add("int16", Token.KEYWORD2);
		keywords.add("uint32", Token.KEYWORD2);
		keywords.add("dbclear", Token.KEYWORD2);
		keywords.add("dbcont", Token.KEYWORD2);
		keywords.add("dbdown", Token.KEYWORD2);
		keywords.add("dbmex", Token.KEYWORD2);
		keywords.add("dbquit", Token.KEYWORD2);
		keywords.add("dbstack", Token.KEYWORD2);
		keywords.add("dbstatus", Token.KEYWORD2);
		keywords.add("dbstep", Token.KEYWORD2);
		keywords.add("dbstop", Token.KEYWORD2);
		keywords.add("dbtype", Token.KEYWORD2);
		keywords.add("dbup", Token.KEYWORD2);

		keywords.add("blkdiag", Token.KEYWORD3);
		keywords.add("eye", Token.KEYWORD3);
		keywords.add("linspace", Token.KEYWORD3);
		keywords.add("logspace", Token.KEYWORD3);
		keywords.add("ones", Token.KEYWORD3);
		keywords.add("rand", Token.KEYWORD3);
		keywords.add("randn", Token.KEYWORD3);
		keywords.add("zeros", Token.KEYWORD3);
		keywords.add("ans", Token.KEYWORD3);
		keywords.add("computer", Token.KEYWORD3);
		keywords.add("eps", Token.KEYWORD3);
		keywords.add("flops", Token.KEYWORD3);
		keywords.add("i", Token.KEYWORD3);
		keywords.add("Inf", Token.KEYWORD3);
		keywords.add("inputname", Token.KEYWORD3);
		keywords.add("j", Token.KEYWORD3);
		keywords.add("NaN", Token.KEYWORD3);
		keywords.add("nargin", Token.KEYWORD3);
		keywords.add("nargout", Token.KEYWORD3);
		keywords.add("pi", Token.KEYWORD3);
		keywords.add("realmax", Token.KEYWORD3);
		keywords.add("realmin", Token.KEYWORD3);
		keywords.add("varargin", Token.KEYWORD3);
		keywords.add("varargout", Token.KEYWORD3);
		keywords.add("calendar", Token.KEYWORD3);
		keywords.add("clock", Token.KEYWORD3);
		keywords.add("cputime", Token.KEYWORD3);
		keywords.add("date", Token.KEYWORD3);
		keywords.add("datenum", Token.KEYWORD3);
		keywords.add("datestr", Token.KEYWORD3);
		keywords.add("datevec", Token.KEYWORD3);
		keywords.add("eomday", Token.KEYWORD3);
		keywords.add("etime", Token.KEYWORD3);
		keywords.add("now", Token.KEYWORD3);
		keywords.add("tic", Token.KEYWORD3);
		keywords.add("toc", Token.KEYWORD3);
		keywords.add("weekday", Token.KEYWORD3);
		keywords.add("cat", Token.KEYWORD3);
		keywords.add("diag", Token.KEYWORD3);
		keywords.add("fliplr", Token.KEYWORD3);
		keywords.add("flipud", Token.KEYWORD3);
		keywords.add("repmat", Token.KEYWORD3);
		keywords.add("reshape", Token.KEYWORD3);
		keywords.add("rot90", Token.KEYWORD3);
		keywords.add("tril", Token.KEYWORD3);
		keywords.add("triu", Token.KEYWORD3);
		keywords.add("compan", Token.KEYWORD3);
		keywords.add("gallery", Token.KEYWORD3);
		keywords.add("hadamard", Token.KEYWORD3);
		keywords.add("hankel", Token.KEYWORD3);
		keywords.add("hilb", Token.KEYWORD3);
		keywords.add("invhilb", Token.KEYWORD3);
		keywords.add("magic", Token.KEYWORD3);
		keywords.add("pascal", Token.KEYWORD3);
		keywords.add("toeplitz", Token.KEYWORD3);
		keywords.add("wilkinson", Token.KEYWORD3);
		keywords.add("abs", Token.KEYWORD3);
		keywords.add("acos", Token.KEYWORD3);
		keywords.add("acosh", Token.KEYWORD3);
		keywords.add("acot", Token.KEYWORD3);
		keywords.add("acoth", Token.KEYWORD3);
		keywords.add("acsc", Token.KEYWORD3);
		keywords.add("acsch", Token.KEYWORD3);
		keywords.add("angle", Token.KEYWORD3);
		keywords.add("asec", Token.KEYWORD3);
		keywords.add("asech", Token.KEYWORD3);
		keywords.add("asin", Token.KEYWORD3);
		keywords.add("asinh", Token.KEYWORD3);
		keywords.add("atan", Token.KEYWORD3);
		keywords.add("atanh", Token.KEYWORD3);
		keywords.add("atan2", Token.KEYWORD3);
		keywords.add("ceil", Token.KEYWORD3);
		keywords.add("complex", Token.KEYWORD3);
		keywords.add("conj", Token.KEYWORD3);
		keywords.add("cos", Token.KEYWORD3);
		keywords.add("cosh", Token.KEYWORD3);
		keywords.add("cot", Token.KEYWORD3);
		keywords.add("coth", Token.KEYWORD3);
		keywords.add("csc", Token.KEYWORD3);
		keywords.add("csch", Token.KEYWORD3);
		keywords.add("exp", Token.KEYWORD3);
		keywords.add("fix", Token.KEYWORD3);
		keywords.add("floor", Token.KEYWORD3);
		keywords.add("gcd", Token.KEYWORD3);
		keywords.add("imag", Token.KEYWORD3);
		keywords.add("lcm", Token.KEYWORD3);
		keywords.add("log", Token.KEYWORD3);
		keywords.add("log2", Token.KEYWORD3);
		keywords.add("log10", Token.KEYWORD3);
		keywords.add("mod", Token.KEYWORD3);
		keywords.add("nchoosek", Token.KEYWORD3);
		keywords.add("real", Token.KEYWORD3);
		keywords.add("rem", Token.KEYWORD3);
		keywords.add("round", Token.KEYWORD3);
		keywords.add("sec", Token.KEYWORD3);
		keywords.add("sech", Token.KEYWORD3);
		keywords.add("sign", Token.KEYWORD3);
		keywords.add("sin", Token.KEYWORD3);
		keywords.add("sinh", Token.KEYWORD3);
		keywords.add("sqrt", Token.KEYWORD3);
		keywords.add("tan", Token.KEYWORD3);
		keywords.add("tanh", Token.KEYWORD3);
		keywords.add("airy", Token.KEYWORD3);
		keywords.add("besselh", Token.KEYWORD3);
		keywords.add("besseli", Token.KEYWORD3);
		keywords.add("besselk", Token.KEYWORD3);
		keywords.add("besselj", Token.KEYWORD3);
		keywords.add("Bessely", Token.KEYWORD3);
		keywords.add("beta", Token.KEYWORD3);
		keywords.add("betainc", Token.KEYWORD3);
		keywords.add("betaln", Token.KEYWORD3);
		keywords.add("ellipj", Token.KEYWORD3);
		keywords.add("ellipke", Token.KEYWORD3);
		keywords.add("erf", Token.KEYWORD3);
		keywords.add("erfc", Token.KEYWORD3);
		keywords.add("erfcx", Token.KEYWORD3);
		keywords.add("erfiny", Token.KEYWORD3);
		keywords.add("expint", Token.KEYWORD3);
		keywords.add("factorial", Token.KEYWORD3);
		keywords.add("gamma", Token.KEYWORD3);
		keywords.add("gammainc", Token.KEYWORD3);
		keywords.add("gammaln", Token.KEYWORD3);
		keywords.add("legendre", Token.KEYWORD3);
		keywords.add("pow2", Token.KEYWORD3);
		keywords.add("rat", Token.KEYWORD3);
		keywords.add("rats", Token.KEYWORD3);
		keywords.add("cart2pol", Token.KEYWORD3);
		keywords.add("cart2sph", Token.KEYWORD3);
		keywords.add("pol2cart", Token.KEYWORD3);
		keywords.add("sph2cart", Token.KEYWORD3);
		keywords.add("abs", Token.KEYWORD3);
		keywords.add("eval", Token.KEYWORD3);
		keywords.add("real", Token.KEYWORD3);
		keywords.add("strings", Token.KEYWORD3);
		keywords.add("deblank", Token.KEYWORD3);
		keywords.add("findstr", Token.KEYWORD3);
		keywords.add("lower", Token.KEYWORD3);
		keywords.add("strcat", Token.KEYWORD3);
		keywords.add("strcmp", Token.KEYWORD3);
		keywords.add("strcmpi", Token.KEYWORD3);
		keywords.add("strjust", Token.KEYWORD3);
		keywords.add("strmatch", Token.KEYWORD3);
		keywords.add("strncmp", Token.KEYWORD3);
		keywords.add("strrep", Token.KEYWORD3);
		keywords.add("strtok", Token.KEYWORD3);
		keywords.add("strvcat", Token.KEYWORD3);
		keywords.add("symvar", Token.KEYWORD3);
		keywords.add("texlabel", Token.KEYWORD3);
		keywords.add("upper", Token.KEYWORD3);
		keywords.add("char", Token.KEYWORD3);
		keywords.add("int2str", Token.KEYWORD3);
		keywords.add("mat2str", Token.KEYWORD3);
		keywords.add("num2str", Token.KEYWORD3);
		keywords.add("sprintf", Token.KEYWORD3);
		keywords.add("sscanf", Token.KEYWORD3);
		keywords.add("str2double", Token.KEYWORD3);
		keywords.add("str2num", Token.KEYWORD3);
		keywords.add("bin2dec", Token.KEYWORD3);
		keywords.add("dec2bin", Token.KEYWORD3);
		keywords.add("dec2hex", Token.KEYWORD3);
		keywords.add("hex2dec", Token.KEYWORD3);
		keywords.add("hex2num", Token.KEYWORD3);
		keywords.add("fclose", Token.KEYWORD3);
		keywords.add("fopen", Token.KEYWORD3);
		keywords.add("fread", Token.KEYWORD3);
		keywords.add("fwrite", Token.KEYWORD3);
		keywords.add("fgetl", Token.KEYWORD3);
		keywords.add("fgets", Token.KEYWORD3);
		keywords.add("fprintf", Token.KEYWORD3);
		keywords.add("fscanf", Token.KEYWORD3);
		keywords.add("feof", Token.KEYWORD3);
		keywords.add("ferror", Token.KEYWORD3);
		keywords.add("frewind", Token.KEYWORD3);
		keywords.add("fseek", Token.KEYWORD3);
		keywords.add("ftell", Token.KEYWORD3);
		keywords.add("sprintf", Token.KEYWORD3);
		keywords.add("sscanf", Token.KEYWORD3);
		keywords.add("dlmread", Token.KEYWORD3);
		keywords.add("dlmwrite", Token.KEYWORD3);
		keywords.add("hdf", Token.KEYWORD3);
		keywords.add("imfinfo", Token.KEYWORD3);
		keywords.add("imread", Token.KEYWORD3);
		keywords.add("imwrite", Token.KEYWORD3);
		keywords.add("textread", Token.KEYWORD3);
		keywords.add("wk1read", Token.KEYWORD3);
		keywords.add("wk1write", Token.KEYWORD3);
		keywords.add("bitand", Token.KEYWORD3);
		keywords.add("bitcmp", Token.KEYWORD3);
		keywords.add("bitor", Token.KEYWORD3);
		keywords.add("bitmax", Token.KEYWORD3);
		keywords.add("bitset", Token.KEYWORD3);
		keywords.add("bitshift", Token.KEYWORD3);
		keywords.add("bitget", Token.KEYWORD3);
		keywords.add("bitxor", Token.KEYWORD3);
		keywords.add("fieldnames", Token.KEYWORD3);
		keywords.add("getfield", Token.KEYWORD3);
		keywords.add("rmfield", Token.KEYWORD3);
		keywords.add("setfield", Token.KEYWORD3);
		keywords.add("struct", Token.KEYWORD3);
		keywords.add("struct2cell", Token.KEYWORD3);
		keywords.add("class", Token.KEYWORD3);
		keywords.add("isa", Token.KEYWORD3);
		keywords.add("cell", Token.KEYWORD3);
		keywords.add("cellfun", Token.KEYWORD3);
		keywords.add("cellstr", Token.KEYWORD3);
		keywords.add("cell2struct", Token.KEYWORD3);
		keywords.add("celldisp", Token.KEYWORD3);
		keywords.add("cellplot", Token.KEYWORD3);
		keywords.add("num2cell", Token.KEYWORD3);
		keywords.add("cat", Token.KEYWORD3);
		keywords.add("flipdim", Token.KEYWORD3);
		keywords.add("ind2sub", Token.KEYWORD3);
		keywords.add("ipermute", Token.KEYWORD3);
		keywords.add("ndgrid", Token.KEYWORD3);
		keywords.add("ndims", Token.KEYWORD3);
		keywords.add("permute", Token.KEYWORD3);
		keywords.add("reshape", Token.KEYWORD3);
		keywords.add("shiftdim", Token.KEYWORD3);
		keywords.add("squeeze", Token.KEYWORD3);
		keywords.add("sub2ind", Token.KEYWORD3);
		keywords.add("cond", Token.KEYWORD3);
		keywords.add("condeig", Token.KEYWORD3);
		keywords.add("det", Token.KEYWORD3);
		keywords.add("norm", Token.KEYWORD3);
		keywords.add("null", Token.KEYWORD3);
		keywords.add("orth", Token.KEYWORD3);
		keywords.add("rank", Token.KEYWORD3);
		keywords.add("rcond", Token.KEYWORD3);
		keywords.add("rref", Token.KEYWORD3);
		keywords.add("rrefmovie", Token.KEYWORD3);
		keywords.add("subspace", Token.KEYWORD3);
		keywords.add("trace", Token.KEYWORD3);
		keywords.add("chol", Token.KEYWORD3);
		keywords.add("inv", Token.KEYWORD3);
		keywords.add("lscov", Token.KEYWORD3);
		keywords.add("lu", Token.KEYWORD3);
		keywords.add("nnls", Token.KEYWORD3);
		keywords.add("pinv", Token.KEYWORD3);
		keywords.add("qr", Token.KEYWORD3);
		keywords.add("balance", Token.KEYWORD3);
		keywords.add("cdf2rdf", Token.KEYWORD3);
		keywords.add("eig", Token.KEYWORD3);
		keywords.add("gsvd", Token.KEYWORD3);
		keywords.add("hess", Token.KEYWORD3);
		keywords.add("poly", Token.KEYWORD3);
		keywords.add("qz", Token.KEYWORD3);
		keywords.add("rsf2csf", Token.KEYWORD3);
		keywords.add("schur", Token.KEYWORD3);
		keywords.add("svd", Token.KEYWORD3);
		keywords.add("expm", Token.KEYWORD3);
		keywords.add("funm", Token.KEYWORD3);
		keywords.add("logm", Token.KEYWORD3);
		keywords.add("sqrtm", Token.KEYWORD3);
		keywords.add("qrdelete", Token.KEYWORD3);
		keywords.add("qrinsert", Token.KEYWORD3);
		keywords.add("bar", Token.KEYWORD3);
		keywords.add("barh", Token.KEYWORD3);
		keywords.add("hist", Token.KEYWORD3);
		keywords.add("hold", Token.KEYWORD3);
		keywords.add("loglog", Token.KEYWORD3);
		keywords.add("pie", Token.KEYWORD3);
		keywords.add("plot", Token.KEYWORD3);
		keywords.add("polar", Token.KEYWORD3);
		keywords.add("semilogx", Token.KEYWORD3);
		keywords.add("semilogy", Token.KEYWORD3);
		keywords.add("subplot", Token.KEYWORD3);
		keywords.add("bar3", Token.KEYWORD3);
		keywords.add("bar3h", Token.KEYWORD3);
		keywords.add("comet3", Token.KEYWORD3);
		keywords.add("cylinder", Token.KEYWORD3);
		keywords.add("fill3", Token.KEYWORD3);
		keywords.add("plot3", Token.KEYWORD3);
		keywords.add("quiver3", Token.KEYWORD3);
		keywords.add("slice", Token.KEYWORD3);
		keywords.add("sphere", Token.KEYWORD3);
		keywords.add("stem3", Token.KEYWORD3);
		keywords.add("waterfall", Token.KEYWORD3);
		keywords.add("clabel", Token.KEYWORD3);
		keywords.add("datetick", Token.KEYWORD3);
		keywords.add("grid", Token.KEYWORD3);
		keywords.add("gtext", Token.KEYWORD3);
		keywords.add("legend", Token.KEYWORD3);
		keywords.add("plotyy", Token.KEYWORD3);
		keywords.add("title", Token.KEYWORD3);
		keywords.add("xlabel", Token.KEYWORD3);
		keywords.add("ylabel", Token.KEYWORD3);
		keywords.add("zlabel", Token.KEYWORD3);
		keywords.add("contour", Token.KEYWORD3);
		keywords.add("contourc", Token.KEYWORD3);
		keywords.add("contourf", Token.KEYWORD3);
		keywords.add("hidden", Token.KEYWORD3);
		keywords.add("meshc", Token.KEYWORD3);
		keywords.add("mesh", Token.KEYWORD3);
		keywords.add("peaks", Token.KEYWORD3);
		keywords.add("surf", Token.KEYWORD3);
		keywords.add("surface", Token.KEYWORD3);
		keywords.add("surfc", Token.KEYWORD3);
		keywords.add("surfl", Token.KEYWORD3);
		keywords.add("trimesh", Token.KEYWORD3);
		keywords.add("trisurf", Token.KEYWORD3);
		keywords.add("coneplot", Token.KEYWORD3);
		keywords.add("contourslice", Token.KEYWORD3);
		keywords.add("isocaps", Token.KEYWORD3);
		keywords.add("isonormals", Token.KEYWORD3);
		keywords.add("isosurface", Token.KEYWORD3);
		keywords.add("reducepatch", Token.KEYWORD3);
		keywords.add("reducevolume", Token.KEYWORD3);
		keywords.add("shrinkfaces", Token.KEYWORD3);
		keywords.add("smooth3", Token.KEYWORD3);
		keywords.add("stream2", Token.KEYWORD3);
		keywords.add("stream3", Token.KEYWORD3);
		keywords.add("streamline", Token.KEYWORD3);
		keywords.add("surf2patch", Token.KEYWORD3);
		keywords.add("subvolume", Token.KEYWORD3);
		keywords.add("griddata", Token.KEYWORD3);
		keywords.add("meshgrid", Token.KEYWORD3);
		keywords.add("area", Token.KEYWORD3);
		keywords.add("box", Token.KEYWORD3);
		keywords.add("comet", Token.KEYWORD3);
		keywords.add("compass", Token.KEYWORD3);
		keywords.add("errorbar", Token.KEYWORD3);
		keywords.add("ezcontour", Token.KEYWORD3);
		keywords.add("ezcontourf", Token.KEYWORD3);
		keywords.add("ezmesh", Token.KEYWORD3);
		keywords.add("ezmeshc", Token.KEYWORD3);
		keywords.add("ezplot", Token.KEYWORD3);
		keywords.add("ezplot3", Token.KEYWORD3);
		keywords.add("ezpolar", Token.KEYWORD3);
		keywords.add("ezsurf", Token.KEYWORD3);
		keywords.add("ezsurfc", Token.KEYWORD3);
		keywords.add("feather", Token.KEYWORD3);
		keywords.add("fill", Token.KEYWORD3);
		keywords.add("fplot", Token.KEYWORD3);
		keywords.add("pareto", Token.KEYWORD3);
		keywords.add("pie3", Token.KEYWORD3);
		keywords.add("plotmatrix", Token.KEYWORD3);
		keywords.add("pcolor", Token.KEYWORD3);
		keywords.add("rose", Token.KEYWORD3);
		keywords.add("quiver", Token.KEYWORD3);
		keywords.add("ribbon", Token.KEYWORD3);
		keywords.add("stairs", Token.KEYWORD3);
		keywords.add("scatter", Token.KEYWORD3);
		keywords.add("scatter3", Token.KEYWORD3);
		keywords.add("stem", Token.KEYWORD3);
		keywords.add("convhull", Token.KEYWORD3);
		keywords.add("delaunay", Token.KEYWORD3);
		keywords.add("dsearch", Token.KEYWORD3);
		keywords.add("inpolygon", Token.KEYWORD3);
		keywords.add("polyarea", Token.KEYWORD3);
		keywords.add("tsearch", Token.KEYWORD3);
		keywords.add("voronoi", Token.KEYWORD3);
		keywords.add("camdolly", Token.KEYWORD3);
		keywords.add("camlookat", Token.KEYWORD3);
		keywords.add("camorbit", Token.KEYWORD3);
		keywords.add("campan", Token.KEYWORD3);
		keywords.add("campos", Token.KEYWORD3);
		keywords.add("camproj", Token.KEYWORD3);
		keywords.add("camroll", Token.KEYWORD3);
		keywords.add("camtarget", Token.KEYWORD3);
		keywords.add("camup", Token.KEYWORD3);
		keywords.add("camva", Token.KEYWORD3);
		keywords.add("camzoom", Token.KEYWORD3);
		keywords.add("daspect", Token.KEYWORD3);
		keywords.add("pbaspect", Token.KEYWORD3);
		keywords.add("view", Token.KEYWORD3);
		keywords.add("viewmtx", Token.KEYWORD3);
		keywords.add("xlim", Token.KEYWORD3);
		keywords.add("ylim", Token.KEYWORD3);
		keywords.add("zlim", Token.KEYWORD3);
		keywords.add("camlight", Token.KEYWORD3);
		keywords.add("diffuse", Token.KEYWORD3);
		keywords.add("lighting", Token.KEYWORD3);
		keywords.add("lightingangle", Token.KEYWORD3);
		keywords.add("material", Token.KEYWORD3);
		keywords.add("specular", Token.KEYWORD3);
		keywords.add("brighten", Token.KEYWORD3);
		keywords.add("bwcontr", Token.KEYWORD3);
		keywords.add("caxis", Token.KEYWORD3);
		keywords.add("colorbar", Token.KEYWORD3);
		keywords.add("colorcube", Token.KEYWORD3);
		keywords.add("colordef", Token.KEYWORD3);
		keywords.add("colormap", Token.KEYWORD3);
		keywords.add("graymon", Token.KEYWORD3);
		keywords.add("hsv2rgb", Token.KEYWORD3);
		keywords.add("rgb2hsv", Token.KEYWORD3);
		keywords.add("rgbplot", Token.KEYWORD3);
		keywords.add("shading", Token.KEYWORD3);
		keywords.add("spinmap", Token.KEYWORD3);
		keywords.add("surfnorm", Token.KEYWORD3);
		keywords.add("whitebg", Token.KEYWORD3);
		keywords.add("autumn", Token.KEYWORD3);
		keywords.add("bone", Token.KEYWORD3);
		keywords.add("contrast", Token.KEYWORD3);
		keywords.add("cool", Token.KEYWORD3);
		keywords.add("copper", Token.KEYWORD3);
		keywords.add("flag", Token.KEYWORD3);
		keywords.add("gray", Token.KEYWORD3);
		keywords.add("hot", Token.KEYWORD3);
		keywords.add("hsv", Token.KEYWORD3);
		keywords.add("jet", Token.KEYWORD3);
		keywords.add("lines", Token.KEYWORD3);
		keywords.add("prism", Token.KEYWORD3);
		keywords.add("spring", Token.KEYWORD3);
		keywords.add("summer", Token.KEYWORD3);
		keywords.add("winter", Token.KEYWORD3);
		keywords.add("orient", Token.KEYWORD3);
		keywords.add("print", Token.KEYWORD3);
		keywords.add("printopt", Token.KEYWORD3);
		keywords.add("saveas", Token.KEYWORD3);
		keywords.add("copyobj", Token.KEYWORD3);
		keywords.add("findobj", Token.KEYWORD3);
		keywords.add("gcbo", Token.KEYWORD3);
		keywords.add("gco", Token.KEYWORD3);
		keywords.add("get", Token.KEYWORD3);
		keywords.add("rotate", Token.KEYWORD3);
		keywords.add("ishandle", Token.KEYWORD3);
		keywords.add("set", Token.KEYWORD3);
		keywords.add("axes", Token.KEYWORD3);
		keywords.add("figure", Token.KEYWORD3);
		keywords.add("image", Token.KEYWORD3);
		keywords.add("light", Token.KEYWORD3);
		keywords.add("line", Token.KEYWORD3);
		keywords.add("patch", Token.KEYWORD3);
		keywords.add("rectangle", Token.KEYWORD3);
		keywords.add("surface", Token.KEYWORD3);
		keywords.add("text Create", Token.KEYWORD3);
		keywords.add("uicontext Create", Token.KEYWORD3);
		keywords.add("capture", Token.KEYWORD3);
		keywords.add("clc", Token.KEYWORD3);
		keywords.add("clf", Token.KEYWORD3);
		keywords.add("clg", Token.KEYWORD3);
		keywords.add("close", Token.KEYWORD3);
		keywords.add("gcf", Token.KEYWORD3);
		keywords.add("newplot", Token.KEYWORD3);
		keywords.add("refresh", Token.KEYWORD3);
		keywords.add("saveas", Token.KEYWORD3);
		keywords.add("axis", Token.KEYWORD3);
		keywords.add("cla", Token.KEYWORD3);
		keywords.add("gca", Token.KEYWORD3);
		keywords.add("propedit", Token.KEYWORD3);
		keywords.add("reset", Token.KEYWORD3);
		keywords.add("rotate3d", Token.KEYWORD3);
		keywords.add("selectmoveresize", Token.KEYWORD3);
		keywords.add("shg", Token.KEYWORD3);
		keywords.add("ginput", Token.KEYWORD3);
		keywords.add("zoom", Token.KEYWORD3);
		keywords.add("dragrect", Token.KEYWORD3);
		keywords.add("drawnow", Token.KEYWORD3);
		keywords.add("rbbox", Token.KEYWORD3);
		keywords.add("dialog", Token.KEYWORD3);
		keywords.add("errordlg", Token.KEYWORD3);
		keywords.add("helpdlg", Token.KEYWORD3);
		keywords.add("inputdlg", Token.KEYWORD3);
		keywords.add("listdlg", Token.KEYWORD3);
		keywords.add("msgbox", Token.KEYWORD3);
		keywords.add("pagedlg", Token.KEYWORD3);
		keywords.add("printdlg", Token.KEYWORD3);
		keywords.add("questdlg", Token.KEYWORD3);
		keywords.add("uigetfile", Token.KEYWORD3);
		keywords.add("uiputfile", Token.KEYWORD3);
		keywords.add("uisetcolor", Token.KEYWORD3);
		keywords.add("uisetfont", Token.KEYWORD3);
		keywords.add("warndlg", Token.KEYWORD3);
		keywords.add("menu", Token.KEYWORD3);
		keywords.add("menuedit", Token.KEYWORD3);
		keywords.add("uicontextmenu", Token.KEYWORD3);
		keywords.add("uicontrol", Token.KEYWORD3);
		keywords.add("uimenu", Token.KEYWORD3);
		keywords.add("dragrect", Token.KEYWORD3);
		keywords.add("findfigs", Token.KEYWORD3);
		keywords.add("gcbo", Token.KEYWORD3);
		keywords.add("rbbox", Token.KEYWORD3);
		keywords.add("selectmoveresize", Token.KEYWORD3);
		keywords.add("textwrap", Token.KEYWORD3);
		keywords.add("uiresume", Token.KEYWORD3);
		keywords.add("uiwait Used", Token.KEYWORD3);
		keywords.add("waitbar", Token.KEYWORD3);
		keywords.add("waitforbuttonpress", Token.KEYWORD3);
		keywords.add("convhull", Token.KEYWORD3);
		keywords.add("cumprod", Token.KEYWORD3);
		keywords.add("cumsum", Token.KEYWORD3);
		keywords.add("cumtrapz", Token.KEYWORD3);
		keywords.add("delaunay", Token.KEYWORD3);
		keywords.add("dsearch", Token.KEYWORD3);
		keywords.add("factor", Token.KEYWORD3);
		keywords.add("inpolygon", Token.KEYWORD3);
		keywords.add("max", Token.KEYWORD3);
		keywords.add("mean", Token.KEYWORD3);
		keywords.add("median", Token.KEYWORD3);
		keywords.add("min", Token.KEYWORD3);
		keywords.add("perms", Token.KEYWORD3);
		keywords.add("polyarea", Token.KEYWORD3);
		keywords.add("primes", Token.KEYWORD3);
		keywords.add("prod", Token.KEYWORD3);
		keywords.add("sort", Token.KEYWORD3);
		keywords.add("sortrows", Token.KEYWORD3);
		keywords.add("std", Token.KEYWORD3);
		keywords.add("sum", Token.KEYWORD3);
		keywords.add("trapz", Token.KEYWORD3);
		keywords.add("tsearch", Token.KEYWORD3);
		keywords.add("var", Token.KEYWORD3);
		keywords.add("voronoi", Token.KEYWORD3);
		keywords.add("del2", Token.KEYWORD3);
		keywords.add("diff", Token.KEYWORD3);
		keywords.add("gradient", Token.KEYWORD3);
		keywords.add("corrcoef", Token.KEYWORD3);
		keywords.add("cov", Token.KEYWORD3);
		keywords.add("conv", Token.KEYWORD3);
		keywords.add("conv2", Token.KEYWORD3);
		keywords.add("deconv", Token.KEYWORD3);
		keywords.add("filter", Token.KEYWORD3);
		keywords.add("filter2", Token.KEYWORD3);
		keywords.add("abs", Token.KEYWORD3);
		keywords.add("angle", Token.KEYWORD3);
		keywords.add("cplxpair", Token.KEYWORD3);
		keywords.add("fft", Token.KEYWORD3);
		keywords.add("fft2", Token.KEYWORD3);
		keywords.add("fftshift", Token.KEYWORD3);
		keywords.add("ifft", Token.KEYWORD3);
		keywords.add("ifft2", Token.KEYWORD3);
		keywords.add("ifftn", Token.KEYWORD3);
		keywords.add("ifftshift", Token.KEYWORD3);
		keywords.add("nextpow2", Token.KEYWORD3);
		keywords.add("unwrap", Token.KEYWORD3);
		keywords.add("cross", Token.KEYWORD3);
		keywords.add("intersect", Token.KEYWORD3);
		keywords.add("ismember", Token.KEYWORD3);
		keywords.add("setdiff", Token.KEYWORD3);
		keywords.add("setxor", Token.KEYWORD3);
		keywords.add("union", Token.KEYWORD3);
		keywords.add("unique", Token.KEYWORD3);
		keywords.add("conv", Token.KEYWORD3);
		keywords.add("deconv", Token.KEYWORD3);
		keywords.add("poly", Token.KEYWORD3);
		keywords.add("polyder", Token.KEYWORD3);
		keywords.add("polyeig", Token.KEYWORD3);
		keywords.add("polyfit", Token.KEYWORD3);
		keywords.add("polyval", Token.KEYWORD3);
		keywords.add("polyvalm", Token.KEYWORD3);
		keywords.add("residue", Token.KEYWORD3);
		keywords.add("roots", Token.KEYWORD3);
		keywords.add("griddata", Token.KEYWORD3);
		keywords.add("interp1", Token.KEYWORD3);
		keywords.add("interp2", Token.KEYWORD3);
		keywords.add("interp3", Token.KEYWORD3);
		keywords.add("interpft", Token.KEYWORD3);
		keywords.add("interpn", Token.KEYWORD3);
		keywords.add("meshgrid", Token.KEYWORD3);
		keywords.add("ndgrid", Token.KEYWORD3);
		keywords.add("spline", Token.KEYWORD3);
		keywords.add("dblquad", Token.KEYWORD3);
		keywords.add("fmin", Token.KEYWORD3);
		keywords.add("fmins", Token.KEYWORD3);
		keywords.add("fzero", Token.KEYWORD3);
		keywords.add("ode45,", Token.KEYWORD3);
		keywords.add("ode113,", Token.KEYWORD3);
		keywords.add("ode15s,", Token.KEYWORD3);
		keywords.add("ode23s,", Token.KEYWORD3);
		keywords.add("ode23t,", Token.KEYWORD3);
		keywords.add("ode23tb", Token.KEYWORD3);
		keywords.add("odefile", Token.KEYWORD3);
		keywords.add("odeget", Token.KEYWORD3);
		keywords.add("odeset", Token.KEYWORD3);
		keywords.add("quad,", Token.KEYWORD3);
		keywords.add("vectorize", Token.KEYWORD3);
		keywords.add("spdiags", Token.KEYWORD3);
		keywords.add("speye", Token.KEYWORD3);
		keywords.add("sprand", Token.KEYWORD3);
		keywords.add("sprandn", Token.KEYWORD3);
		keywords.add("sprandsym", Token.KEYWORD3);
		keywords.add("find", Token.KEYWORD3);
		keywords.add("full", Token.KEYWORD3);
		keywords.add("sparse", Token.KEYWORD3);
		keywords.add("spconvert", Token.KEYWORD3);
		keywords.add("nnz", Token.KEYWORD3);
		keywords.add("nonzeros", Token.KEYWORD3);
		keywords.add("nzmax", Token.KEYWORD3);
		keywords.add("spalloc", Token.KEYWORD3);
		keywords.add("spfun", Token.KEYWORD3);
		keywords.add("spones", Token.KEYWORD3);
		keywords.add("colmmd", Token.KEYWORD3);
		keywords.add("colperm", Token.KEYWORD3);
		keywords.add("dmperm", Token.KEYWORD3);
		keywords.add("randperm", Token.KEYWORD3);
		keywords.add("symmmd", Token.KEYWORD3);
		keywords.add("symrcm", Token.KEYWORD3);
		keywords.add("condest", Token.KEYWORD3);
		keywords.add("normest", Token.KEYWORD3);
		keywords.add("bicg", Token.KEYWORD3);
		keywords.add("bicgstab", Token.KEYWORD3);
		keywords.add("cgs", Token.KEYWORD3);
		keywords.add("cholinc", Token.KEYWORD3);
		keywords.add("cholupdate", Token.KEYWORD3);
		keywords.add("gmres", Token.KEYWORD3);
		keywords.add("luinc", Token.KEYWORD3);
		keywords.add("pcg", Token.KEYWORD3);
		keywords.add("qmr", Token.KEYWORD3);
		keywords.add("qr", Token.KEYWORD3);
		keywords.add("qrdelete", Token.KEYWORD3);
		keywords.add("qrinsert", Token.KEYWORD3);
		keywords.add("qrupdate", Token.KEYWORD3);
		keywords.add("eigs", Token.KEYWORD3);
		keywords.add("svds", Token.KEYWORD3);
		keywords.add("spparms", Token.KEYWORD3);
		keywords.add("lin2mu", Token.KEYWORD3);
		keywords.add("mu2lin", Token.KEYWORD3);
		keywords.add("sound", Token.KEYWORD3);
		keywords.add("soundsc", Token.KEYWORD3);
		keywords.add("auread", Token.KEYWORD3);
		keywords.add("auwrite", Token.KEYWORD3);
		keywords.add("wavread", Token.KEYWORD3);
		keywords.add("wavwrite", Token.KEYWORD3);
		keywords.add("[Keywords 6]", Token.KEYWORD3);
		keywords.add("addpath", Token.KEYWORD3);
		keywords.add("doc", Token.KEYWORD3);
		keywords.add("docopt", Token.KEYWORD3);
		keywords.add("help", Token.KEYWORD3);
		keywords.add("helpdesk", Token.KEYWORD3);
		keywords.add("helpwin", Token.KEYWORD3);
		keywords.add("lasterr", Token.KEYWORD3);
		keywords.add("lastwarn", Token.KEYWORD3);
		keywords.add("lookfor", Token.KEYWORD3);
		keywords.add("partialpath", Token.KEYWORD3);
		keywords.add("path", Token.KEYWORD3);
		keywords.add("pathtool", Token.KEYWORD3);
		keywords.add("profile", Token.KEYWORD3);
		keywords.add("profreport", Token.KEYWORD3);
		keywords.add("rmpath", Token.KEYWORD3);
		keywords.add("type", Token.KEYWORD3);
		keywords.add("ver", Token.KEYWORD3);
		keywords.add("version", Token.KEYWORD3);
		keywords.add("web", Token.KEYWORD3);
		keywords.add("what", Token.KEYWORD3);
		keywords.add("whatsnew", Token.KEYWORD3);
		keywords.add("which", Token.KEYWORD3);
		keywords.add("clear", Token.KEYWORD3);
		keywords.add("disp", Token.KEYWORD3);
		keywords.add("length", Token.KEYWORD3);
		keywords.add("load", Token.KEYWORD3);
		keywords.add("mlock", Token.KEYWORD3);
		keywords.add("munlock", Token.KEYWORD3);
		keywords.add("openvar", Token.KEYWORD3);
		keywords.add("pack", Token.KEYWORD3);
		keywords.add("save", Token.KEYWORD3);
		keywords.add("saveas", Token.KEYWORD3);
		keywords.add("size", Token.KEYWORD3);
		keywords.add("who", Token.KEYWORD3);
		keywords.add("whos", Token.KEYWORD3);
		keywords.add("workspace", Token.KEYWORD3);
		keywords.add("clc", Token.KEYWORD3);
		keywords.add("echo", Token.KEYWORD3);
		keywords.add("format", Token.KEYWORD3);
		keywords.add("home", Token.KEYWORD3);
		keywords.add("more", Token.KEYWORD3);
		keywords.add("cd", Token.KEYWORD3);
		keywords.add("copyfile", Token.KEYWORD3);
		keywords.add("delete", Token.KEYWORD3);
		keywords.add("diary", Token.KEYWORD3);
		keywords.add("dir", Token.KEYWORD3);
		keywords.add("edit", Token.KEYWORD3);
		keywords.add("fileparts", Token.KEYWORD3);
		keywords.add("fullfile", Token.KEYWORD3);
		keywords.add("inmem", Token.KEYWORD3);
		keywords.add("ls", Token.KEYWORD3);
		keywords.add("matlabroot", Token.KEYWORD3);
		keywords.add("mkdir", Token.KEYWORD3);
		keywords.add("open", Token.KEYWORD3);
		keywords.add("pwd", Token.KEYWORD3);
		keywords.add("tempdir", Token.KEYWORD3);
		keywords.add("tempname", Token.KEYWORD3);
		keywords.add("matlabrc", Token.KEYWORD3);
		keywords.add("quit", Token.KEYWORD3);

	}

}
