/* CVS $Id: PeopleVocab.java,v 1.1 2007-12-14 12:49:09 stain Exp $ */
package uk.ac.man.cs.img.mygrid.provenance.knowledge.ontology.jena; 
import com.hp.hpl.jena.ontology.DatatypeProperty;
import com.hp.hpl.jena.ontology.OntClass;
import com.hp.hpl.jena.ontology.OntModel;
import com.hp.hpl.jena.ontology.OntModelSpec;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;
/**
 * Vocabulary definitions from people.owl 
 * @author Auto-generated by schemagen on 24 Jan 2006 10:56 
 */
public class PeopleVocab {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.mygrid.org.uk/people.owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final DatatypeProperty FAMILY_NAME = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/people.owl#familyName" );
    
    public static final DatatypeProperty FIRST_NAME = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/people.owl#firstName" );
    
    public static final DatatypeProperty USER_NAME = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/people.owl#userName" );
    
    public static final DatatypeProperty CRYPTED_PASSWORD = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/people.owl#cryptedPassword" );
    
    public static final DatatypeProperty GROUP = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/people.owl#group" );
    
    public static final DatatypeProperty MIDDLE_NAME = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/people.owl#middleName" );
    
    public static final DatatypeProperty ORGANIZATION = m_model.createDatatypeProperty( "http://www.mygrid.org.uk/people.owl#organization" );
    
    public static final OntClass PERSON = m_model.createClass( "http://www.mygrid.org.uk/people.owl#Person" );
    
}
